all: FP_A FP_B FP_C FP_D

FP_A: FP_A.cpp
	g++ -g -Wall FP_A.cpp -o FP_A

FP_B: FP_B.c
	gcc -g -Wall FP_B.c -o FP_B

FP_C: FP_C.cpp
	g++ -g -Wall FP_C.cpp -o FP_C

FP_D: FP_D.cpp
	g++ -g -Wall FP_D.cpp -o FP_D

clean:
	rm -f FP_A FP_B FP_C FP_D
